"use client"
import "./globals.css";
import { Inter } from "next/font/google";
import Login from "./login";
import { getSession } from "@/lib/utils";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [user] = useState(true);

  if (!user) {
    return (
      <html lang="en">
        <body className={inter.className}>
          {" "}
          
        </body>
      </html>
    );
  }
  return (
    <html lang="en">
      <body className={inter.className}>
          <main>
            {!user?<Login />:children}
          </main>
      </body>
    </html>
  );
}
